version: '3.1'

services:
  zoo1:
    image: myzookeeper:3.5
    restart: always
    hostname: zoo1
    volumes:
      - /Users/huangzhe/me/docker-data/zookeeper/zoo1:/data
      - /Users/huangzhe/me/docker-data/ext:/mnt
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: myzookeeper:3.5
    restart: always
    hostname: zoo2
    volumes:
      - /Users/huangzhe/me/docker-data/zookeeper/zoo2:/data
      - /Users/huangzhe/me/docker-data/ext:/mnt
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: myzookeeper:3.5
    restart: always
    hostname: zoo3
    volumes:
      - /Users/huangzhe/me/docker-data/zookeeper/zoo3:/data
      - /Users/huangzhe/me/docker-data/ext:/mnt
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

  solr1:
    image: mysolr:1.0
    restart: always
    hostname: solr1
    volumes:
      - /Users/huangzhe/me/docker-data/ext:/mnt
      - /Users/huangzhe/me/docker-data/solr/solr1:/solr/server/solr
      - /Users/huangzhe/me/docker-data/solr/webapp:/solr/server/solr-webapp/webapp
    ports:
      - 8984:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      SOLR_ZOO: zoo1:2181,zoo2:2181,zoo3:2181/solr

  solr2:
    image: mysolr:1.0
    restart: always
    hostname: solr2
    volumes:
      - /Users/huangzhe/me/docker-data/ext:/mnt
      - /Users/huangzhe/me/docker-data/solr/solr2:/solr/server/solr
      - /Users/huangzhe/me/docker-data/solr/webapp:/solr/server/solr-webapp/webapp
    ports:
      - 8985:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      SOLR_ZOO: zoo1:2181,zoo2:2181,zoo3:2181/solr

  solr3:
    image: mysolr:1.0
    restart: always
    hostname: solr3
    volumes:
      - /Users/huangzhe/me/docker-data/ext:/mnt
      - /Users/huangzhe/me/docker-data/solr/solr3:/solr/server/solr
      - /Users/huangzhe/me/docker-data/solr/webapp:/solr/server/solr-webapp/webapp
    ports:
      - 8986:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      SOLR_ZOO: zoo1:2181,zoo2:2181,zoo3:2181/solr
