version: '3.1'

services:
  zoo1:
    image: hzdan/myzookeeper:3.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: hzdan/myzookeeper:3.5
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: hzdan/myzookeeper:3.5
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888

  solr1:
    image: hzdan/mysolr7.2:1.0
    restart: always
    hostname: solr1
    ports:
      - 8984:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      SOLR_ZOO: zoo1:2181,zoo2:2181,zoo3:2181/solr

  solr2:
    image: hzdan/mysolr7.2:1.0
    restart: always
    hostname: solr2
    ports:
      - 8985:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      SOLR_ZOO: zoo1:2181,zoo2:2181,zoo3:2181/solr

  solr3:
    image: hzdan/mysolr7.2:1.0
    restart: always
    hostname: solr3
    ports:
      - 8986:8983
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    environment:
      SOLR_ZOO: zoo1:2181,zoo2:2181,zoo3:2181/solr
